# Generated by Django 4.2.30 on 2026-06-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation_placeholder', models.CharField(blank=True, default='', max_length=200)),
                ('meaning', models.TextField(blank=True, default='')),
                ('usage_scene', models.TextField(blank=True, default='')),
                ('era', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('needs_revision', '需修订')], default='pending', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.TextField()),
                ('scope', models.CharField(blank=True, default='', max_length=200)),
                ('is_common', models.BooleanField(default=False)),
                ('contributed_by', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('elder', '长辈'), ('youth', '晚辈')], default='elder', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='terms.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa_notation', models.CharField(blank=True, default='', max_length=200)),
                ('tone_description', models.CharField(blank=True, default='', max_length=200)),
                ('phonetic_spelling', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('contributed_by', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('elder', '长辈'), ('youth', '晚辈')], default='elder', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='terms.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('example_sentence', '例句'), ('kinship_term', '人物关系称呼'), ('synonym', '近义词'), ('mandarin_translation', '普通话对照'), ('image_association', '图片联想'), ('family_note', '家庭备注')], max_length=50)),
                ('content', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('contributed_by', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('elder', '长辈'), ('youth', '晚辈')], default='elder', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='terms.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
