# Generated by Django 4.2.30 on 2026-06-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('narrator', models.CharField(blank=True, default='', max_length=100)),
                ('recorder', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('era', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField()),
                ('mandarin_summary', models.TextField(blank=True, default='')),
                ('original_fragments', models.TextField(blank=True, default='')),
                ('elder_revision_notes', models.TextField(blank=True, default='')),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_elder_confirm', '待长辈确认'), ('organized', '已整理'), ('needs_supplement', '需补充')], default='draft', max_length=30)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_terms', models.ManyToManyField(blank=True, related_name='related_stories', to='terms.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('change_note', models.CharField(blank=True, default='', max_length=500)),
                ('contributed_by', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('elder', '长辈'), ('youth', '晚辈')], default='youth', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='terms.story')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
