# Generated by Django 4.2.30 on 2026-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_story_storyrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('era_start', models.CharField(blank=True, default='', max_length=50)),
                ('era_end', models.CharField(blank=True, default='', max_length=50)),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='stories', to='terms.location'),
        ),
        migrations.AddField(
            model_name='term',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='terms', to='terms.location'),
        ),
    ]
