# Generated by Django 4.2.30 on 2026-06-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_location_story_locations_term_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('supplement_pronunciation', '补充发音'), ('confirm_meaning', '确认释义'), ('add_example_sentence', '补写例句'), ('organize_story', '整理故事'), ('supplement_location', '补充地点'), ('verify_kinship_term', '核对人物称呼')], max_length=50)),
                ('status', models.CharField(choices=[('unclaimed', '待认领'), ('in_progress', '进行中'), ('pending_elder_confirm', '待长辈确认'), ('needs_rework', '需返工'), ('completed', '已完成'), ('archived', '已归档')], default='unclaimed', max_length=30)),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10)),
                ('assignee', models.CharField(blank=True, default='', max_length=100)),
                ('assistants', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('acceptance_criteria', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_locations', models.ManyToManyField(blank=True, related_name='heritage_tasks', to='terms.location')),
                ('related_stories', models.ManyToManyField(blank=True, related_name='heritage_tasks', to='terms.story')),
                ('related_terms', models.ManyToManyField(blank=True, related_name='heritage_tasks', to='terms.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('rework_reason', models.TextField(blank=True, default='')),
                ('is_final_confirmation', models.BooleanField(default=False)),
                ('operated_by', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('elder', '长辈'), ('youth', '晚辈')], default='youth', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='terms.heritagetask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
